// Copyright (c) OdbDesignInfoClient Contributors. All rights reserved.
// Licensed under the MIT License.

using System.Text.Json.Serialization;

namespace OdbDesignInfoClient.Services.Api.Dtos;

/// <summary>
/// Data Transfer Object for Component JSON responses from OdbDesignServer REST API.
/// Maps to protobuf message: Odb.Lib.Protobuf.ProductModel.Component.
/// </summary>
/// <remarks>
/// JSON field names use camelCase as generated by protobuf's MessageToJsonString().
/// All fields are nullable to handle optional protobuf fields gracefully.
/// </remarks>
public sealed class ComponentDto
{
    /// <summary>
    /// Gets the reference designator (e.g., "U1", "R102", "C1").
    /// Unique identifier for the component instance on the board.
    /// </summary>
    [JsonPropertyName("refDes")]
    public string? RefDes { get; init; }

    /// <summary>
    /// Gets the part name/number (e.g., "STM32F407VGT6", "10K").
    /// Links to the Parts library.
    /// </summary>
    [JsonPropertyName("partName")]
    public string? PartName { get; init; }

    /// <summary>
    /// Gets the package/footprint information.
    /// Contains physical dimensions and pin geometry.
    /// </summary>
    [JsonPropertyName("package")]
    public PackageDto? Package { get; init; }

    /// <summary>
    /// Gets the zero-based index of the component in the design's component list.
    /// </summary>
    [JsonPropertyName("index")]
    public uint? Index { get; init; }

    /// <summary>
    /// Gets the board side where component is placed.
    /// Values: "TOP", "BOTTOM", or "BS_NONE" (unspecified).
    /// </summary>
    [JsonPropertyName("side")]
    public string? Side { get; init; }

    /// <summary>
    /// Gets the part library entry with attributes.
    /// Contains component value, manufacturer, etc.
    /// </summary>
    [JsonPropertyName("part")]
    public PartDto? Part { get; init; }
}
